/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResolvenAiRouteImport } from './routes/resolven-ai'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as IndexRouteImport } from './routes/index'

const ResolvenAiRoute = ResolvenAiRouteImport.update({
  id: '/resolven-ai',
  path: '/resolven-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/resolven-ai': typeof ResolvenAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/resolven-ai': typeof ResolvenAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/resolven-ai': typeof ResolvenAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modules' | '/resolven-ai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modules' | '/resolven-ai'
  id: '__root__' | '/' | '/modules' | '/resolven-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesRoute: typeof ModulesRoute
  ResolvenAiRoute: typeof ResolvenAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resolven-ai': {
      id: '/resolven-ai'
      path: '/resolven-ai'
      fullPath: '/resolven-ai'
      preLoaderRoute: typeof ResolvenAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesRoute: ModulesRoute,
  ResolvenAiRoute: ResolvenAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
